Initial PR for repo
Vualto/offline-shaka pull request #1
Opened 2020-09-29 14:46 UTC by bengo1990

Please pull this down and test from the readme.

2020-09-29 15:03 UTC, PerritonBranch requested changes, later dismissed

2020-09-29 15:03 UTC, PerritonBranch commented on README.md
> +To enable https, you must create a certificate to self authenticate for local host:
```suggestion
To enable https, you must create a certificate to self authenticate for localhost: 
```

2020-09-29 15:03 UTC, PerritonBranch commented on README.md
> +- Input the password from the above, complete all prompts.This creates locahost.pem
```suggestion
- Input the password from the above, complete all prompts. This creates locahost.pem.
```

2020-09-29 15:03 UTC, PerritonBranch commented on README.md
> +- Create a private key - ensure openssl is installed and input the following command: openssl genrsa -aes256 -out localhost.key 2048
```suggestion
- Create a private key - ensure openssl is installed and input the following command: `openssl genrsa -aes256 -out localhost.key 2048`
```

2020-09-29 15:03 UTC, PerritonBranch commented on README.md
> +- Create the certificate by inputting the following command: openssl req -days 3650 -new -newkey rsa:2048 -key localhost.key -x509 -out localhost.pem
```suggestion
- Create the certificate by inputting the following command: `openssl req -days 3650 -new -newkey rsa:2048 -key localhost.key -x509 -out localhost.pem`
```

2020-09-29 15:03 UTC, PerritonBranch commented on README.md
> +Assuming everything has been set up correctly, you should now see the Shaka Player working locally with https
```suggestion
Assuming everything has been set up correctly, you should now see the Shaka Player working locally with https.
```

2020-09-29 15:03 UTC, PerritonBranch commented on README.md
> +By default, Content Name is set to “vualto-drm-encrypted-video”
```suggestion
By default, Content Name is set to “vualto-drm-encrypted-video”.
```

2020-09-29 15:37 UTC, bengo1990 commented on README.md
> +To enable https, you must create a certificate to self authenticate for local host:
Actioned.

2020-09-29 15:38 UTC, bengo1990 commented on README.md
> +- Input the password from the above, complete all prompts.This creates locahost.pem
Actioned.

2020-09-29 15:38 UTC, bengo1990 commented on README.md
> +- Create a private key - ensure openssl is installed and input the following command: openssl genrsa -aes256 -out localhost.key 2048
Actioned.

2020-09-29 15:39 UTC, bengo1990 commented on README.md
> +- Create the certificate by inputting the following command: openssl req -days 3650 -new -newkey rsa:2048 -key localhost.key -x509 -out localhost.pem
Actioned.

2020-09-29 15:39 UTC, bengo1990 commented on README.md
> +Assuming everything has been set up correctly, you should now see the Shaka Player working locally with https
Actioned.

2020-09-29 15:39 UTC, bengo1990 commented on README.md
> +By default, Content Name is set to “vualto-drm-encrypted-video”
Actioned.

2020-10-13 15:46 UTC, somerobmitchell approved these changes

2020-10-13 15:46 UTC, merged